
[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

[theme]
base="dark"
primaryColor="#5a635f"
backgroundColor="#3eb575"
secondaryBackgroundColor="#f9f9f9"
textColor="#12231a"
font="sans serif"
borderColor = "#1c4432"
