
[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

[theme]
base="dark"
primaryColor="#f9f9f9"
backgroundColor="#004c0c"
secondaryBackgroundColor="#bababa"
textColor="#ffffff"
font="sans serif"
borderColor = "#f9f9f9"
